Device: cuda
Dataset: cityscapes, Train set: 2975, Val set: 500
[!] Retrain
Traceback (most recent call last):
  File "main.py", line 532, in <module>
    main()
  File "main.py", line 472, in main
    outputs = model(images)
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chenht/DeepLabv3plus/DeepLabV3Plus-Pytorch/network/utils.py", line 15, in forward
    features = self.backbone(x)
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chenht/DeepLabv3plus/DeepLabV3Plus-Pytorch/network/utils.py", line 80, in forward
    x = module(x)
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chenht/DeepLabv3plus/DeepLabV3Plus-Pytorch/network/backbone/resnet.py", line 110, in forward
    out = self.bn3(out)
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 168, in forward
    return F.batch_norm(
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/torch/nn/functional.py", line 2421, in batch_norm
    return torch.batch_norm(
RuntimeError: CUDA out of memory. Tried to allocate 144.00 MiB (GPU 0; 23.70 GiB total capacity; 18.61 GiB already allocated; 1014.00 MiB free; 18.72 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF